updates about creators.doc-platform section
vrcd-community/vrchat-docs-localization pull request #10
Opened 2023-11-22 15:50 UTC by slime-butter

2023-11-22 16:51 UTC, Misaka-L commented
另外给我好好写 commit comment 啊（恼

2023-11-22 16:56 UTC, Misaka-L requested changes
还需要修改

2023-11-22 16:56 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +当 Android 玩家加入您的世界时，您可能需要调整它的某些方面。Android 移动设备上的玩家将无法访问 VR 控制器，就像 VR 玩家无法访问触摸屏一样。
需要润色，母语中文的人不会用 “访问” 一次来指“使用控制器”

2023-11-22 16:56 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +您可以使用 [UdonSharp](../../../udonsharp.docs.vrchat.com/udonsharp.md) 来检测您世界中的 Android 玩家：
太多 ../ 不如用绝对路径.....

2023-11-22 16:56 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +- 使用 [IsUserInVR](../../worlds/udon/players/players.md) 检查本地玩家是否在 VR 中。
同上

2023-11-22 16:56 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +好消息是：如果您的世界在 Quest 2 上运行良好，它也有可能会在 Android 移动设备上运行良好。手机和平板电脑的分辨率通常低于 VR 头戴式设备，并且性能方面会比 VR 少更多恶心的问题。
考虑换掉下“恶心”？

2023-11-22 16:56 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +在 VRChat 世界中快速迭代时，在 Unity 编辑器或 Steam 版本的 VRChat 中测试它们可能很方便。操纵杆游戏手柄可以作为 VRChat 移动控制屏幕的合适替代品。
“移动控制屏幕”是什么？

2023-11-22 16:56 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +## 结论：给玩家一个流畅的用户体验
考虑删去“用户”或者更换成“游戏”？

2023-11-22 16:56 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +- 请听取用户反馈。
粗体

2023-11-22 16:56 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/cross-platform-setup.md
> +设置跨平台世界或虚拟形象实际上非常简单！您所要做的就是使用重复的项目来构建某某资产的 Android 版本，并将其上传为与 VRChat PC 资产相同的内容 ID。客户端会自动判断需要下载的资产版本是哪一个。
“某某”->“某个”

2023-11-22 17:02 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/quest-content-optimization.md
> +如果您上传的虚拟形象或虚拟形象世界上的虚拟形象大大超出了我们的推荐范围，则该世界或虚拟形象可能会从公共访问中被移除。
这个咱不太清楚该怎么翻译。。。所以直接硬凑了一个，毕竟原文指的是 public access

2023-11-22 17:07 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +当 Android 玩家加入您的世界时，您可能需要调整它的某些方面。Android 移动设备上的玩家将无法访问 VR 控制器，就像 VR 玩家无法访问触摸屏一样。
豪德

2023-11-22 17:07 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +您可以使用 [UdonSharp](../../../udonsharp.docs.vrchat.com/udonsharp.md) 来检测您世界中的 Android 玩家：
豪德，咱把所有的都做一下修改

2023-11-22 17:07 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +- 使用 [IsUserInVR](../../worlds/udon/players/players.md) 检查本地玩家是否在 VR 中。
收到

2023-11-22 17:07 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +好消息是：如果您的世界在 Quest 2 上运行良好，它也有可能会在 Android 移动设备上运行良好。手机和平板电脑的分辨率通常低于 VR 头戴式设备，并且性能方面会比 VR 少更多恶心的问题。
是咱画蛇添足了(；′⌒`)

2023-11-22 17:07 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +在 VRChat 世界中快速迭代时，在 Unity 编辑器或 Steam 版本的 VRChat 中测试它们可能很方便。操纵杆游戏手柄可以作为 VRChat 移动控制屏幕的合适替代品。
应该指的就是手机屏幕。。。咱去改一下

2023-11-22 17:07 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +## 结论：给玩家一个流畅的用户体验
豪德

2023-11-22 17:07 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +- 请听取用户反馈。
豪德（当时是有点懒uwu）

2023-11-22 17:35 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/quest-content-limitations.md
> +目前，如果您上传的虚拟形象或虚拟形象世界含有超出我们推荐数据的虚拟形象，则该世界或虚拟形象可能会从公共访问中删除。
咱不太清楚这个该怎么翻译，毕竟原文就是 public access

2023-11-22 17:35 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/quest-content-optimization.md
> +同样的普遍规则适用于装配在世界中的虚拟形象。请记住，同一个房间中可能有 10 个或更多的玩家，因此您需要非常严格地预算三角面的使用情况。**我们建议您的虚拟形象面数低于 10000 个三角形**。
这个咱也不太清楚具体情况，因为目前这个虚拟形象的概念咱不太清楚是（作为世界的一部分的虚拟形象），还是（只能通过某些渠道比如世界才能获得的单一获取渠道虚拟形象）

2023-11-22 17:35 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/quest-content-optimization.md
> +对纹理大小的留意在虚拟形象和世界中都适用，但请记住，您应该减小虚拟形象纹理的大小，因为在单个房间中您将加载多个虚拟形象（但您只会加载一个世界）。
豪德，咱继续去修改

2023-11-22 17:39 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/cross-platform-setup.md
> +设置跨平台世界或虚拟形象实际上非常简单！您所要做的就是使用重复的项目来构建某某资产的 Android 版本，并将其上传为与 VRChat PC 资产相同的内容 ID。客户端会自动判断需要下载的资产版本是哪一个。
豪德

2023-11-22 17:39 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/quest-content-limitations.md
> +FinalIK	| 自定义 FinalIK 组件在 VRChat Quest 中的虚拟形象上完全禁用。<br>FinalIK 组件是资源使用量海量的来源。我们目前不打算在Quest上启用它们。
咱去进尽力试一下

2023-11-22 17:41 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/quest-content-limitations.md
> +FinalIK	| 自定义 FinalIK 组件在 VRChat Quest 中的虚拟形象上完全禁用。<br>FinalIK 组件是资源使用量海量的来源。我们目前不打算在Quest上启用它们。
是 FinalIK 那一段，“资源使用量海量的来源”

2023-11-24 06:25 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/quest-content-limitations.md
> +FinalIK	| 自定义 FinalIK 组件在 VRChat Quest 中的虚拟形象上完全禁用。<br>FinalIK 组件是资源使用量海量的来源。我们目前不打算在Quest上启用它们。
修改里

2023-11-24 06:25 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/quest-content-optimization.md
> +同样的普遍规则适用于装配在世界中的虚拟形象。请记住，同一个房间中可能有 10 个或更多的玩家，因此您需要非常严格地预算三角面的使用情况。**我们建议您的虚拟形象面数低于 10000 个三角形**。
改好里

2023-11-24 06:25 UTC, slime-butter commented on docs/creators.vrchat.com/platforms/android/quest-content-optimization.md
> +对纹理大小的留意在虚拟形象和世界中都适用，但请记住，您应该减小虚拟形象纹理的大小，因为在单个房间中您将加载多个虚拟形象（但您只会加载一个世界）。
改好里

2023-11-24 06:55 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/quest-content-optimization.md
> +如果您上传的虚拟形象或虚拟形象世界上的虚拟形象大大超出了我们的推荐范围，则该世界或虚拟形象可能会从公共访问中被移除。
”则该世界或虚拟形象可能会从公共访问中被移除。“ 可以更换成 "则该世界或虚拟形象可能会被设为私有"

2023-11-24 06:55 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/quest-content-limitations.md
> +目前，如果您上传的虚拟形象或虚拟形象世界含有超出我们推荐数据的虚拟形象，则该世界或虚拟形象可能会从公共访问中删除。
”则该世界或虚拟形象可能会从公共访问中被删除。“ 可以更换成 "则该世界或虚拟形象可能会被设为私有"

2023-11-24 06:59 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +跨平台发布您的 VRChat 世界是让更多玩家能够享受它的好方法。有许多 VRChat 玩家都在 Android 上，因此您值得创建您的 VRChat 世界的 Android 版本。
"有许多 VRChat 玩家都在 Android 上" 可以修改为 "有许多 VRChat 玩家在使用 Andorid 设备游玩"
"因此您值得创建您的 VRChat 世界的 Android 版本。" 可以修改为 "因此值得您创建您的 VRChat 世界的 Android 版本。"

2023-11-24 07:02 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +然而，移动端玩家和VR玩家将体验到完全不同的世界！在本指南中，我们将解释一些使您移动端上的 VRChat 世界更加舒适和愉快的方法。
英文与中文之间应留有空格  
"解释一些使您移动端上的 VRChat 世界更加舒适和愉快的方法。" 可以修改为 "介绍一些使您的 VRChat 世界在移动端上体验更加舒适愉快的方法。"

2023-11-24 07:03 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +当 Android 玩家加入您的世界时，您可能需要手动调整它的某些表现。Android 移动端上的玩家将无法使用 VR 控制器，就像 VR 玩家无法使用触控屏一样。
"表现" => "行为"

2023-11-24 07:03 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +- 本地化文本。与其他平台相比，移动玩家使用的语言范围要广泛得多。
"移动玩家" => "移动端玩家"

2023-11-24 07:05 UTC, Misaka-L reviewed
还需要修改和润色

2023-11-24 07:08 UTC, Misaka-L requested changes
还需要修改和润色

2023-11-24 08:07 UTC, Misaka-L requested changes
就差一个小错误

2023-11-24 08:07 UTC, Misaka-L commented on docs/creators.vrchat.com/platforms/android/android-best-practices.md
> +然而，移动端玩家和 VR 玩家将体验到完全不同的世界！在本指南中，介绍一些使您的 VRChat 世界在移动端上体验更加舒适愉快的方法。。
多了个句号

2023-11-24 08:17 UTC, Misaka-L approved these changes
没啥问题了，小问题我给你改了。过了

2023-11-24 08:18 UTC, merged