文档部分润色
vrcd-community/vrchat-docs-localization pull request #15
Opened 2023-11-25 17:30 UTC by flower-elf

警告：仅完成了部分工作，不过这些应该可以安全合并

2023-11-25 18:14 UTC, Misaka-L requested changes

2023-11-25 18:14 UTC, Misaka-L commented on docs/docs.vrchat.com/OVERVIEW/additional-options/vrchat-configuration-window.md
>  Oculus Quest 2 被设置为 4x MSAA。
“被设置” -> “应设置”

2023-11-25 18:14 UTC, Misaka-L commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +如果您想在模型菜单中返回，可以将摇杆置于中间（默认）位置并按下扳机键，这样您就能返回上一级菜单了。
语句不通顺

2023-11-25 18:14 UTC, Misaka-L commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +默认情况下，您可以通过点击对应手的摇杆来弹出圆盘菜单。
摇杆可以被点击吗....

2023-11-25 18:14 UTC, Misaka-L commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +默认情况下，您可以通过点击对应手的摇杆来弹出圆盘菜单。
摇杆可以被点击吗....

2023-11-25 18:14 UTC, Misaka-L commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +如果有摇杆，您可以通过点击摇杆来弹出圆盘菜单。
摇杆可以被点击吗....

2023-11-25 18:14 UTC, Misaka-L commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +默认情况下，通过点击并按住控制器顶部的菜单按钮来弹出圆盘菜单。
“点击并按住”有点令人难以理解...

2023-11-25 18:14 UTC, Misaka-L commented on docs/docs.vrchat.com/OVERVIEW/getting-started.md
> +我们提供了一些用于了解各种[控件](/docs.vrchat.com/OVERVIEW/controls/controls.md)的文档。如果您需要帮助或技术支持，请访问 [https://help.vrchat.com/](https://help.vrchat.com/)。
控件是啥

2023-11-25 18:14 UTC, Misaka-L commented on docs/docs.vrchat.com/OVERVIEW/welcome-to-vrchat.md
> +欢迎来到 VRChat 文档！我们将在这里介绍 VRChat 的各个部分，包括应用内d的各系统与功能，以及SDK中的组件。这也包括可以在您创作时给予您帮助的有用提示。
typo 错字受

2023-11-25 18:14 UTC, Misaka-L commented on docs/docs.vrchat.com/SYSTEM/avatar-fallback-system.md
> +小刚的模型现在将作为她对翠花的备用模型出现，而不是一个“性能屏蔽”的机器人！她可以通过她的模型菜单选择自己的备用模型。她可以从 VRChat 的选择中选择一个“默认模型”，也可以上传自己的模型。
语句不通顺

2023-11-25 18:15 UTC, flower-elf commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +默认情况下，您可以通过点击对应手的摇杆来弹出圆盘菜单。
非处理范围，此类问题延后修复，目前正在进行清理工作

2023-11-25 18:17 UTC, flower-elf commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +默认情况下，您可以通过点击对应手的摇杆来弹出圆盘菜单。
目前有非常多的地方有问题，当前的修改也只是使用替换来进行基本修复。语句的通顺性处理会在这些工作完成后进行

2023-11-25 18:19 UTC, Misaka-L requested changes

2023-11-25 18:19 UTC, Misaka-L commented on docs/docs.vrchat.com/GUIDES/setup-2fa.md
> +::: danger ❗️账号丢失的风险！
不出意外的话 VitePress 没办法正确处理 tip 标题里的 markdown 标题....

2023-11-25 18:20 UTC, Misaka-L commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +默认情况下，您可以通过点击对应手的摇杆来弹出圆盘菜单。
也就是会在之后的 pr 里修复的意思吗

2023-11-25 18:21 UTC, flower-elf commented on docs/docs.vrchat.com/GUIDES/setup-2fa.md
> +::: danger ❗️账号丢失的风险！
原文件如此，唯一的修改是批量替换。如果影响巨大，那么我看看怎么处理

2023-11-25 18:22 UTC, flower-elf commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +默认情况下，您可以通过点击对应手的摇杆来弹出圆盘菜单。
> 也就是会在之后的 pr 里修复的意思吗

是的，目前暂时不考虑通顺度，否则压根忙不过来

2023-11-25 18:23 UTC, flower-elf commented on docs/docs.vrchat.com/OVERVIEW/controls/action-menu.md
> +默认情况下，您可以通过点击对应手的摇杆来弹出圆盘菜单。
不过如果可能，我会一并修复这些问题

2023-11-25 18:25 UTC, Misaka-L commented on docs/docs.vrchat.com/GUIDES/setup-2fa.md
> +::: danger ❗️账号丢失的风险！
目前看来至少没有造成外观上的问题，但是不保证之后不出问题

2023-11-26 02:39 UTC, Misaka-L commented on docs/docs.vrchat.com/ADVANCED-GUIDES/using-vrchat-in-a-virtual-machine.md
> +    std::cout << "Hyper-V id:" << std::endl;
好像把不应该替换的东西替换了......

2023-11-26 02:39 UTC, Misaka-L commented on docs/docs.vrchat.com/ADVANCED-GUIDES/using-vrchat-in-a-virtual-machine.md
> +Hyper-V id:
同上

2023-11-26 02:48 UTC, flower-elf commented on docs/docs.vrchat.com/ADVANCED-GUIDES/using-vrchat-in-a-virtual-machine.md
> +    std::cout << "Hyper-V id:" << std::endl;
链接问题已修复，其余只是字符串大小写问题，不影响，反而提高可读性

2023-11-26 03:47 UTC, Misaka-L requested changes
都是小问题

2023-11-26 03:47 UTC, Misaka-L commented on docs/docs.vrchat.com/SYSTEM/avatar-particle-system-limits.md
> +ps_max_total_emission | 模型上所有粒子系统之间允许的最大发射
最大发射....啥？

2023-11-26 03:47 UTC, Misaka-L commented on docs/docs.vrchat.com/SYSTEM/vrchat-safety-and-trust-system.md
> +启用后，安全系统将被设置为自定义模式，并关闭所有玩家的所有功能。文本将出现在屏幕中间，解释刚刚发生的事情。此操作将直接覆盖您的自定义设置。所有玩家的模型都将被隐藏，非好友玩家的所有语音都将被禁用。
玩家 _模型_ 的所有功能

2023-11-26 04:43 UTC, Misaka-L approved these changes

2023-11-26 04:46 UTC, merged