一部分 Udon 介绍性文档 (index.md) 的翻译
vrcd-community/vrchat-docs-localization pull request #37
Opened 2023-12-30 16:24 UTC by Misaka-L

close #36

2024-01-26 05:16 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +## 上传你的世界
上传您的世界

2024-01-26 05:17 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +当你[注册一个 VRChat 账号](https://vrchat.com/home/register)之后，你就可以使用 Build & Test 了。如果你想要发布你的世界来让其他人也可以游玩，你需要在 VRChat 上花费一些时间：游玩不同的世界，交一些朋友然后获得一些灵感！
这里同样需要注意“您”的用词习惯

2024-01-26 06:02 UTC, slime-butter reviewed
修改部分用词错误，添加翻译内容，优化小部分用词

2024-01-26 06:12 UTC, slime-butter requested changes
修改部分用词错误，添加翻译内容，优化小部分用词

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +你可以在菜单栏点击 **VRChatSDK > Udon Graph** 或直接点击 UdonBehaviour 组件上的 **Open Udon Graph** 按钮来打开 Udon 节点图窗口。
您可以在菜单栏点击 **VRChatSDK > Udon Graph** 或直接点击 UdonBehaviour 组件上的 **Open Udon Graph** 按钮来打开 Udon 节点图窗口。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +Udon 节点图（Udon Node Graph）是创建 Udon 程序的默认接口。本章节会说明如何使用它。如果你想直接查看示例，请参阅 [Udon 示例场景](/creators.vrchat.com/worlds/examples/udon-example-scene/)。
Udon 节点图（Udon Node Graph）是创建 Udon 程序的默认接口。本章节会说明如何使用它。如果您想直接查看示例，请参阅 [Udon 示例场景](/creators.vrchat.com/worlds/examples/udon-example-scene/)。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +你也可以通过点击标签一角的 X 来关闭标签页。请注意，节点图标签页并不是“真正的”的标签页，当你点击不同的标签页时，它只会重新加载节点图。
您也可以通过点击标签一角的 X 来关闭标签页。请注意，节点图标签页并不是“真正的”的标签页，当您点击不同的标签页时，它只会重新加载节点图。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +There is a "Highlight flow" toggle on the topbar, which, when enabled, will highlight the nodes connected via the flow edges, allowing you to quickly see how does the program arrive to the particular
这部分是不是要删掉

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +如果你不知道 **发送自定义事件（Sending a Custom Event）** 是什么意思也是正常的。先学习节点图中的流是你理解节点图的工作方式的第一步。
如果您不知道 发送自定义事件（Sending a Custom Event） 是什么意思也是正常的。先学习节点图中的流是您理解节点图的工作方式的第一步。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +安装以下任意一个快捷键再在节点图内点击你想创建节点的地方来创建对应的节点。
安装以下任意一个快捷键再在节点图内点击您想创建节点的地方来创建对应的节点。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
>  Creating nodes via Drag and Drop this way creates Variables that are tied to your GameObject or Component, so you'll see a new variable appear in the Variables window, and a node which is actually a
如果要向游戏对象或组件添加交互，可以将它们从 hierarchy 拖放到 graph 中。例如，您可以通过将“Light”标题拖动到 graph 上来拖放 Light 组件。
这是获取对 Light 组件引用的简单方法，方便您去捣鼓它。
通过拖放操作创建的节点会创建一个绑定到游戏对象或组件的变量，因此您会看到一个新变量和一个节点出现在 Variables 窗口中，该节点是一个“Get Variable”节点，其会自动设置为抓取新的组件。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
>  You can create variables of any type by pressing the **+** button in the Variables pane of the Graph Sidebar. Then you can drag and drop the variable name onto the graph to create a "Get Variable" no
您可以通过点击 Graph Sidebar 下 Variables 面板中的 + 按钮来创建任何类型的变量。之后您可以将相应变量名称拖放到面板上以创建“Get Variable”节点，在拖动时按住 Ctrl 键以创建“Set Variable”节点，或按住 Alt 键以创建“On Variable Changed”节点。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
>  Press the **Spacebar** to open up Quick Search, then type in the first few letters of the class you want to interact with.
点击 空格 打开快捷搜索，输入您想要搜索的类别的前几个词

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
>  This method of searching works best if you know Unity's basic classes and object types. There are other ways of searching, see: [Searching for nodes](/creators.vrchat.com/worlds/udon/graph/searching-
如果您了解 Unity 的基本类和对象类型，则此类搜索方法效果最好。当然还有其他的搜索方法，请参阅：[搜索节点](https://github.com/creators.vrchat.com/worlds/udon/graph/searching-for-nodes)

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +节点图会在后台定时自动编译。编译时你会看到节点图右上角在闪动，当编译完成时会显示绿色或在编译失败时显示红色。你点击状态盒（Status Box）查看生成的“汇编”代码或者编译失败时出现的错误。
节点图会在后台定时自动编译。编译时您会看到节点图右上角在闪动，当编译完成时会显示绿色或在编译失败时显示红色。点击状态盒（Status Box）可以查看生成的“汇编”代码或者编译失败时出现的错误。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +:::
这里需要表上一个译者注释：
::: warning 🧑‍💻译者注释
这部分的内容已经过时了。
:::

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +使用 VRChat SDK 窗口来进行本地测试。把你的内容打包成一个离线世界并启动 VRChat 客户端可以让你测试和对象的交互和 VRCPlayerAPI，但是会花费更长的时间。
使用 VRChat SDK 窗口来进行本地测试。把您的内容打包成一个离线世界并启动 VRChat 客户端可以让您测试和对象的交互和 VRCPlayerAPI，但是会花费更长的时间。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +如果你需要测试同步变量和网络世界，你需要两个客户端。你可以使用“客户端数量（Number of Clients）”输入框启动最多 8 个加入本地测试世界的客户端。它们会以相同的用户名显示，但是它们都会被视为单独的玩家这样子就可以测试你的交互了。
如果您需要测试同步变量和网络世界，您会需要两个客户端。您可以使用“客户端数量（Number of Clients）”输入框启动最多 8 个本地测试世界的客户端。它们会以相同的用户名显示，但是它们都会被视为单独的玩家，这样就可以测试您的交互了。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +::: danger 设置你的本地客户端路径
::: danger 设置您的本地客户端路径

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +如果“强制桌面模式（Force Non-VR）”不关注，请到 VRChat SDK 窗口的“设置”选项卡并设置你的 VRChat 客户端路径为你的客户端实际安装的位置。
如果“强制桌面模式（Force Non-VR）”不关注，请到 VRChat SDK 窗口的“设置”选项卡并设置您的 VRChat 客户端路径为您的客户端实际安装的位置。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +## 上传你的世界
上传您的世界

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/graph/index.md
> +当你[注册一个 VRChat 账号](https://vrchat.com/home/register)之后，你就可以使用 Build & Test 了。如果你想要发布你的世界来让其他人也可以游玩，你需要在 VRChat 上花费一些时间：游玩不同的世界，交一些朋友然后获得一些灵感！
当您[注册一个 VRChat 账号](https://vrchat.com/home/register)之后，您就可以使用 Build & Test 了。如果您想要发布您的世界来让其他人也可以游玩，您需要在 VRChat 上花费一些时间：游玩不同的世界，交一些朋友然后获得一些灵感！

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/players/index.md
> +您可以在世界中通过 VRCPlayerApi 和玩家交互。每个玩家都有一个 VRCPlayerApi 对象，并且你的世界会在玩家加入/离开的时候在所有 UdonBehaviours 上分别触发 `OnPlayerJoined` / `OnPlayerLeft` 事件。
您可以在世界中通过 VRCPlayerApi 和玩家交互。每个玩家都有一个 VRCPlayerApi 对象，并且您的世界会在玩家加入/离开的时候在所有 UdonBehaviours 上分别触发 OnPlayerJoined / OnPlayerLeft 事件。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/players/index.md
> +这个页面包括一些基本的节点。由于你可以用 VRCPlayerApi 对象做很多事情，我们把一些节点分类到了以下页面。
这个页面包括一些基本的节点。由于您可以用 VRCPlayerApi 对象做很多事情，我们把一些节点分类到了以下页面。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/players/index.md
> +在你尝试玩家的获取或者修改任何东西，请确保 IsValid 返回 true。如果一个玩家已经离开了事件但是你依然在引用这个玩家对应的 VRCPlayerApi 对象，则会返回 false。为了更方便地在节点图中使用，请搜索通用的“IsValid”方法，该方法适用于任何对象，因为它为“true”和“false”提供了单独的流程。
在您尝试玩家的获取或者修改任何东西，请确保 IsValid 返回 true。如果一个玩家已经离开了事件但是您依然在引用这个玩家对应的 VRCPlayerApi 对象，则会返回 false。为了更方便地在节点图中使用，请搜索通用的“IsValid”方法，该方法适用于任何对象，因为它为“true”和“false”提供了单独的流程。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/players/index.md
> +关闭玩家捡起物品和使用世界中的 VRCPickup 对象的能力。这个属性默认为 _on_，所以当你想关掉玩家捡起物品的能力时，你只需要使用这个方法。
关闭玩家捡起物品和使用世界中的 VRCPickup 对象的能力。这个属性默认为 on，所以当您想关掉玩家捡起物品的能力时，您只需要使用这个方法。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/players/index.md
> +告诉你一个玩家是不是所输入 GameObject 的 Owner，对于同步来说非常重要。
告诉您一个玩家是不是所输入 GameObject 的 Owner，对于同步来说非常重要。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/players/index.md
> +告诉你一个玩家是否在使用 VR 头显。
告诉您一个玩家是否在使用 VR 头显。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/players/index.md
> +### 获取可用语言
这部分是否需要保留英文原文

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/video-players/index.md
> +为什么你需要在两者之间二选一？
为什么您需要在两者之间二选一？

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/video-players/index.md
> +这也适用于后续加入世界的玩家。如果你的世界中有 2 个视频播放器在运行，那么后续加入世界的玩家就会发现他们必须发送两个视频请求。如果不在任何处理，则会尝试同时发送这些请求，但会失败。如果您的世界中时有多个视频播放器，您就必须考虑到这一点。
这也适用于后续加入世界的玩家。如果您的世界中有 2 个视频播放器在运行，那么后续加入世界的玩家就会发现他们必须发送两个视频请求。如果不在任何处理，则会尝试同时发送这些请求，但会失败。如果您的世界中时有多个视频播放器，您就必须考虑到这一点。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/video-players/index.md
> +当你在编辑器内设置您的视频播放器时，你需要在 Video URL 输入框内提供一个 URL，或者粘贴一个 URL 到预制件内提供的 VRCUrlInputField。
当您在编辑器内设置您的视频播放器时，您需要在 Video URL 输入框内提供一个 URL，或者粘贴一个 URL 到预制件内提供的 VRCUrlInputField。

2024-01-26 06:12 UTC, slime-butter commented on docs/creators.vrchat.com/worlds/udon/video-players/index.md
> +如果您的世界面向的玩家在一些网络条件较为特殊的国家和地区，你会需要考虑其他的视频托管平台或者一些变通方法。
如果您的世界面向的玩家在一些网络条件较为特殊的国家和地区，您会需要考虑其他的视频托管平台或者一些变通方法。

2024-01-26 12:40 UTC, flower-elf requested changes
docs/creators.vrchat.com/worlds/index.md
第四行，不通顺

2024-01-26 16:49 UTC, flower-elf approved these changes

2024-01-27 03:58 UTC, slime-butter requested changes
部分语法语句结构更改，保留原义

2024-01-27 04:10 UTC, slime-butter approved these changes

2024-01-27 04:11 UTC, slime-butter approved these changes

2024-01-27 04:12 UTC, merged