Avatar Dynamic translation
vrcd-community/vrchat-docs-localization pull request #73
Opened 2024-02-23 04:35 UTC by Anteness

（略）

2024-02-23 05:34 UTC, slime-butter requested changes
minor character change

2024-02-23 05:34 UTC, slime-butter commented on docs/creators.vrchat.com/avatars/avatar-dynamics/debugging-avatar-dynamics.md
> +在游戏内，您可以使用 "模型调试"（Avatar Overlay）选项在游戏中以可视化方式实时显示[物理骨骼](/creators.vrchat.com/avatars/avatar-dynamics/physbones)和[触发器](/creators.vrchat.com/avatars/avatar-dynamics/contacts)。这对于查看什么事情正在发生，或什么对象是否已正确设置
模型调试 -> 模型叠加显示层（暂定）
如果有更好的翻译请随时comment

2024-02-23 05:34 UTC, slime-butter commented on docs/creators.vrchat.com/avatars/avatar-dynamics/physbones.md
> + 如果设置为 **Ignore** ，根骨骼将不会出现物理效果。这对于头发等物体非常有用，因为您可以只在根骨骼上设置一个 Physbone 组件即可作用于所有子级头发骨骼！
如果设置为 **Ignore** ，根骨骼将不会运动，并忽略物理效果。这对于头发等物体非常有用，因为您只需在根骨骼上设置一个 Physbone 组件即可作用于所有子级头发骨骼！
> 原文中指出 the root bone will not move 并不单指不会被物理效果影响，应同样代表任何施加于骨骼的动画无效，所以需要单独解释

2024-02-23 05:34 UTC, slime-butter commented on docs/creators.vrchat.com/avatars/avatar-dynamics/physbones.md
> +相反，复制要用作根骨骼的骨骼，并将要动画的所有子骨骼重新连接到新的复制根骨骼。这应该在 Blender 中完成。社区制作的工具（如 Cat's Blender 插件）可以为您完成此操作。
相反，复制要用作根骨骼的骨骼，并将要施加动画的所有子骨骼重新连接到新的根骨骼。此操作应在 Blender 中完成。社区工具（如 Cat's Blender 插件）可以为您完成此操作。

2024-03-28 14:01 UTC, Anteness commented on docs/creators.vrchat.com/avatars/avatar-dynamics/physbones.md
> +相反，复制要用作根骨骼的骨骼，并将要动画的所有子骨骼重新连接到新的复制根骨骼。这应该在 Blender 中完成。社区制作的工具（如 Cat's Blender 插件）可以为您完成此操作。
Cat插件已经过时了，可以考虑是否删去或注释适用blender版本
其他的小bug暂时不处理吧

2024-03-28 14:06 UTC, merged